SELECT * FROM DOCUMENTALES;
SELECT * FROM USUARIO;
SELECT * FROM TRANSMISIONES;
UPDATE DOCUMENTALES SET Año = 2020 WHERE idDocumentales = 5;
UPDATE USUARIO SET usu_telefono = 3115678432 WHERE usu_alias = "ninja";
DELETE FROM TRANSMISIONES WHERE id_trans=16;






